export const data = {
	bio: {
		name: 'Sibasish Mohanty',
		title: 'Full stack developer',
		email: 'smsibasish@gmail.com',
		website: 'https://sibasish.me',
		twitter: 'https://twitter.com/smsibasish',
		github: 'https://github.com/sibasishm',
		stackoverflow: 'https://stackoverflow.com/users/9128145/sibasish-mohanty',
		linkedin: 'https://www.linkedin.com/in/sibasish-mohanty',
		behance: 'https://www.behance.net/Sibasish19',
	},
	position: [
		{
			id: '1',
			role: 'Senior software engineer',
			company: 'Goodera',
			location: 'Bangalore, Karnataka',
			startDate: '08/13/2018',
			achievements: [
				'Built custom dashboards for our top notch clients to keep track of their CSR activities.',
				'Automated many monotonous tasks for a hassle free developing experience across teams.',
				'Mentoring juniors and reviewing their works (code review, documentation review, etc.)',
			],
		},
		{
			id: '2',
			role: 'UI/UX design intern',
			company: 'Indian Institue of Technology',
			location: 'Guwahati, Assam',
			startDate: '05/05/2017',
			endDate: '08/05/2017',
			achievements: [
				'Collaborated with Prof. Uday Kumar to understand design patterns and principles.',
				'Researched extensively on the perception of design in India and awareness of design education in India.',
				'Applied my understanding and research to develop a interactive and responsive website prototype.',
			],
		},
		{
			id: '3',
			role: 'UI/UX design intern',
			company: 'Phoenix Robotics',
			location: 'Bhubaneswar, Odisha',
			startDate: '07/12/2015',
			endDate: '02/05/2016',
			achievements: [
				'Developed the UI Wireframes and mockups for the current website.',
				'Designed some posters, sponsorship brochures, pamphlets for publicity purposes.',
			],
		},
	],
	education: [
		{
			id: '1',
			certificate: 'B.TECH Electronics and Communication Engineering',
			school: 'National Institue of Technology',
			location: 'Rourkela, Odisha',
			startYear: '2014',
			endYear: '2018',
			grade: '8.32 / 10',
		},
		{
			id: '2',
			certificate: 'Intermediate in Science',
			school: 'Saraswati Vidya Mandir, Nilakantha Nagar',
			location: 'Berhampur, Odisha',
			startYear: '2011',
			endYear: '2013',
			grade: '88.83%',
		},
		{
			id: '3',
			certificate: 'Matriculation',
			school: 'Saraswati Sishu Mandir, Nimakhandi ',
			location: 'Berhampur, Odisha',
			startYear: '2010',
			endYear: '2011',
			grade: '94.83%',
		},
	],
};
